{{- $runtimeSecret := include "mcpgateway.runtimeSecretName" . -}}
{{- define "mcpgateway.runtimeSecretEnv" -}}
- name: MCPGW_DB_URL
  valueFrom:
    secretKeyRef:
      name: {{ include "mcpgateway.runtimeSecretName" . }}
      key: {{ .Values.secrets.keys.dbURL | quote }}
- name: MCPGW_NATS_URL
  valueFrom:
    secretKeyRef:
      name: {{ include "mcpgateway.runtimeSecretName" . }}
      key: {{ .Values.secrets.keys.natsURL | quote }}
      optional: true
- name: MCPGW_OIDC_ISSUER
  valueFrom:
    secretKeyRef:
      name: {{ include "mcpgateway.runtimeSecretName" . }}
      key: {{ .Values.secrets.keys.oidcIssuer | quote }}
      optional: true
- name: MCPGW_OIDC_AUDIENCE
  valueFrom:
    secretKeyRef:
      name: {{ include "mcpgateway.runtimeSecretName" . }}
      key: {{ .Values.secrets.keys.oidcAudience | quote }}
      optional: true
- name: OTEL_EXPORTER_OTLP_ENDPOINT
  valueFrom:
    secretKeyRef:
      name: {{ include "mcpgateway.runtimeSecretName" . }}
      key: {{ .Values.secrets.keys.otlpEndpoint | quote }}
      optional: true
{{- end -}}
