{{- if .Values.vault.enabled }}
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ include "mcpgateway.fullname" . }}-runtime
  labels:
    {{- include "mcpgateway.labels" . | nindent 4 }}
spec:
  type: kv-v2
  mount: {{ .Values.vault.mount | quote }}
  path: {{ .Values.vault.path | quote }}
  refreshAfter: {{ .Values.vault.refreshAfter | quote }}
  destination:
    create: true
    name: {{ .Values.secrets.existingSecret | quote }}
  vaultAuthRef: {{ .Values.vault.authRef | quote }}
{{- end }}
